notifications:
  email: false

jobs:
  include:
    # perform a linux build
    - services: docker
      before_install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:deadsnakes/ppa -y
        - sudo apt update
        - sudo apt install python3.8
        - sudo apt-get -y install python3-pip
        - sudo apt-get -y install python3-setuptools
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade setuptools
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        # install Python 3 and make sure it's on PATH as 'python3'
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to an API token in Travis settings

install:
  - python3 -m pip install cibuildwheel==1.12.0

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse/

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
